version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Run Build step"
          command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" RedstoneLauncher.sln /Build Release
      - store_artifacts:
          path: .\bin\Release\RedstoneLauncher.exe