version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - store_artifacts:
          path: .\bin\Release\RedstoneLauncher.exe